import {
  LocalProvider,
  Office031Config,
  Extension,
  OfficeMailItem,
  CallLogItem,
  DesktopPhoneModel,
  PhoneContact,
} from '../types';

export const DEFAULT_LOCAL_PROVIDERS: LocalProvider[] = [
  {
    id: 'prov-telkom',
    name: 'Telkom SA Enterprise Voice',
    slug: 'telkom',
    providerType: 'National Tier 1',
    host: 'sip.kzn.telkom.co.za',
    port: 5060,
    protocol: 'UDP',
    registrationStatus: 'registered',
    latencyMs: 14,
    authUsername: 'kzn-031-tr-9408800',
    durbanPopLocation: 'Durban Central Exchange (Kingsmead Metro)',
    codecs: ['G.711a (PCMA)', 'G.729', 'Opus'],
    isPrimary: true,
    didRanges: ['+27 (031) 940 8800 - 8899', '+27 (031) 301 0000 - 0999'],
    registeredSince: '2026-09-09 08:00:00 (Uptime 99.98%)',
    channelCapacity: 30,
    activeChannels: 2,
  },
  {
    id: 'prov-vodacom',
    name: 'Vodacom Business OneConnect',
    slug: 'vodacom',
    providerType: 'Mobile Network Carrier',
    host: 'ims-dbn.vodacom.co.za',
    port: 5061,
    protocol: 'TLS',
    registrationStatus: 'registered',
    latencyMs: 18,
    authUsername: 'vodabiz-durban-trunk',
    durbanPopLocation: 'Umhlanga Ridge Data Centre',
    codecs: ['G.711a (PCMA)', 'Opus HD', 'AMR-WB'],
    isPrimary: false,
    didRanges: ['+27 (031) 820 0000 - 0999'],
    registeredSince: '2026-09-09 08:15:00',
    channelCapacity: 20,
    activeChannels: 0,
  },
  {
    id: 'prov-mtn',
    name: 'MTN Business Cloud SIP',
    slug: 'mtn',
    providerType: 'Mobile Network Carrier',
    host: 'sip.kzn.mtnbusiness.co.za',
    port: 5060,
    protocol: 'UDP',
    registrationStatus: 'registered',
    latencyMs: 22,
    authUsername: 'mtn-dbn-sip-994',
    durbanPopLocation: 'Durban North Switch Facility',
    codecs: ['G.711a (PCMA)', 'G.729'],
    isPrimary: false,
    didRanges: ['+27 (031) 880 1000 - 1999'],
    registeredSince: '2026-09-09 08:10:00',
    channelCapacity: 15,
    activeChannels: 1,
  },
  {
    id: 'prov-switchtel',
    name: 'Switch Telecom SA',
    slug: 'switchtel',
    providerType: 'VoIP Specialist',
    host: 'sip.switchtel.co.za',
    port: 5060,
    protocol: 'UDP',
    registrationStatus: 'registered',
    latencyMs: 16,
    authUsername: 'swtel-031-pilot',
    durbanPopLocation: 'Teraco DB1 Riverhorse Valley',
    codecs: ['G.711a (PCMA)', 'G.711u', 'G.729'],
    isPrimary: false,
    didRanges: ['+27 (031) 942 0000 - 0499'],
    registeredSince: '2026-09-09 08:30:00',
    channelCapacity: 25,
    activeChannels: 0,
  },
  {
    id: 'prov-liquid',
    name: 'Liquid Intelligent Tech',
    slug: 'liquid',
    providerType: 'Fibre SIP Trunk',
    host: 'sip.liquidtelecom.co.za',
    port: 5061,
    protocol: 'TLS',
    registrationStatus: 'offline',
    latencyMs: 26,
    authUsername: 'lit-dbn-trunk-01',
    durbanPopLocation: 'Mayville Metro POP',
    codecs: ['G.711a (PCMA)', 'G.729'],
    isPrimary: false,
    didRanges: ['+27 (031) 913 5000 - 5999'],
    channelCapacity: 50,
    activeChannels: 0,
  },
];

export const DEFAULT_OFFICE_031_CONFIG: Office031Config = {
  mainNumber: '031 940 8800',
  formattedInternational: '+27 31 940 8800',
  areaCode: '031',
  regionName: 'Durban / eThekwini Metro, KwaZulu-Natal',
  providerId: 'prov-telkom',
  switchboardExtension: '101',
  callerIdName: 'GEX Office Switchboard HQ',

  // Desktop Phone Auto-Provisioning Binding
  deskPhoneProvisioned: true,
  deskPhoneModel: 'yealink-t48u',
  deskPhoneMac: '00:15:65:4F:9B:12',
  deskPhoneIp: '192.168.1.101',
  lineKeyIndex: 1,
  autoAnswerIntercom: true,

  // Office Mail (Voicemail on 031 number)
  voicemailEnabled: true,
  voicemailNumber: '*97',
  voicemailPin: '4890',
  voicemailEmailNotify: 'sello.ncwani@gmail.com',
  voicemailEmailAttachMp3: true,
  voicemailAiTranscript: true,
  mwiLampEnabled: true,
  greetingMode: 'custom',
  greetingAudioTitle: 'GEX Durban HQ Corporate Greeting',
  greetingScript:
    'Thank you for calling GEX PBX (Global Extension Exchange) Durban Regional Office at 031 940 8800. All our switchboard lines are currently assisting clients. Please leave your name, company, and contact number after the beep, or press 0 for operator assistance.',
  ringDurationBeforeMailSeconds: 18,
};

export const DEFAULT_EXTENSIONS: Extension[] = [
  {
    id: 'ext-101',
    extensionNumber: '101',
    name: 'Switchboard / Operator',
    department: 'Front Desk & Central Operator',
    status: 'available',
    isCurrentUser: true,
    email: 'switchboard@gexpbx.co.za',
    role: 'Operator',
    mobileNumber: '+27 82 555 1010',
    directDid: '031 940 8800',
    allowOutbound: true,
    outboundCli: '031 940 8800',
    webRtcUsername: 'ext101-switchboard',
    webRtcPassword: 'WSS-Sec!9408800-Op',
    sipDomain: 'sip.kzn.telkom.co.za',
    deviceType: 'SIP Deskphone',
    pwaInstalled: true,
    notes: 'Main Durban Metro Inbound Reception & Transfer Console',
  },
  {
    id: 'ext-102',
    extensionNumber: '102',
    name: 'Thabo Cele (Sales Desk)',
    department: 'Commercial & Sales',
    status: 'available',
    email: 'thabo.c@gexpbx.co.za',
    role: 'Agent',
    mobileNumber: '+27 83 412 8840',
    directDid: '031 940 8802',
    allowOutbound: true,
    outboundCli: '031 940 8800',
    webRtcUsername: 'ext102-tcele',
    webRtcPassword: 'PWA-Web!102-Agent',
    sipDomain: 'sip.kzn.telkom.co.za',
    deviceType: 'PWA Mobile (iOS/Android)',
    pwaInstalled: true,
    notes: 'Outbound sales agent using iPhone PWA Softphone on 4G/5G',
  },
  {
    id: 'ext-103',
    extensionNumber: '103',
    name: 'Fatima Patel (Finance)',
    department: 'Financial Ops & Billing',
    status: 'in_call',
    currentCallWith: 'Standard Bank KZN (031 374 1100)',
    email: 'fatima.p@gexpbx.co.za',
    role: 'Manager',
    mobileNumber: '+27 82 890 3311',
    directDid: '031 940 8803',
    allowOutbound: true,
    outboundCli: '031 940 8803',
    webRtcUsername: 'ext103-fpatel',
    webRtcPassword: 'PWA-Web!103-Fin',
    sipDomain: 'sip.kzn.telkom.co.za',
    deviceType: 'PWA Desktop',
    pwaInstalled: true,
    notes: 'Financial credit control & client direct DID dialer',
  },
  {
    id: 'ext-104',
    extensionNumber: '104',
    name: 'Sipho Zulu (Port Logistics)',
    department: 'Harbour Logistics & Pier 1',
    status: 'available',
    email: 'sipho.z@gexpbx.co.za',
    role: 'Agent',
    mobileNumber: '+27 71 672 9012',
    directDid: '031 940 8804',
    allowOutbound: true,
    outboundCli: '031 940 8800',
    webRtcUsername: 'ext104-szulu',
    webRtcPassword: 'PWA-Web!104-Harbour',
    sipDomain: 'sip.kzn.telkom.co.za',
    deviceType: 'PWA Mobile (iOS/Android)',
    pwaInstalled: true,
    notes: 'Mobile logistics agent at Durban Port using Android PWA softphone',
  },
  {
    id: 'ext-105',
    extensionNumber: '105',
    name: 'Brendan Naidoo (IT & NOC)',
    department: 'PBX Infrastructure & NOC',
    status: 'available',
    email: 'brendan.n@gexpbx.co.za',
    role: 'Supervisor',
    mobileNumber: '+27 84 333 9081',
    directDid: '031 940 8805',
    allowOutbound: true,
    outboundCli: '031 940 8800',
    webRtcUsername: 'ext105-bnaidoo',
    webRtcPassword: 'PWA-NOC!105-Sys',
    sipDomain: 'sip.kzn.telkom.co.za',
    deviceType: 'PWA Desktop',
    pwaInstalled: true,
    notes: 'PBX Trunk routing, WebRTC signaling & network QoS engineer',
  },
  {
    id: 'ext-106',
    extensionNumber: '106',
    name: 'Sello Ncwani (Field Ops)',
    department: 'Field Operations & Mobile',
    status: 'available',
    email: 'sello.ncwani@gmail.com',
    role: 'Manager',
    mobileNumber: '076 101 5283',
    mobileCarrier: 'Vodacom',
    mobileTwinningMode: 'simultaneous',
    directDid: '031 940 8806',
    allowOutbound: true,
    outboundCli: '031 940 8800',
    webRtcUsername: 'ext106-sncwani',
    webRtcPassword: 'PWA-Web!106-Vodacom',
    sipDomain: 'sip.kzn.telkom.co.za',
    deviceType: 'PWA Mobile (iOS/Android)',
    pwaInstalled: true,
    notes: 'Vodacom Mobile (076 101 5283) linked with active Mobile Twinning & 031 Outbound CLI presentation',
  },
];

export const DESKTOP_PHONE_MODELS: DesktopPhoneModel[] = [
  {
    id: 'yealink-t48u',
    brand: 'Yealink',
    model: 'T48U / T58W',
    displayName: 'Yealink T48U Executive Touch + EXP50 Sidecar',
    description: '7-inch color touch screen, 16 SIP accounts, dual USB ports, Opus support, EXP50 20-key color BLF module.',
    screenType: 'Color Touch LCD 7"',
    blfKeys: 20,
    sipAccounts: 16,
    imageAccent: 'slate-800',
    configFormat: 'yealink_cfg',
  },
  {
    id: 'grandstream-grp2616',
    brand: 'Grandstream',
    model: 'GRP2616',
    displayName: 'Grandstream GRP2616 Carrier-Grade Switchboard',
    description: 'Dual LCD screens with 48 virtual BLF/speed dial keys, integrated dual-band Wi-Fi, noise shield technology.',
    screenType: 'Executive Dual-Screen',
    blfKeys: 16,
    sipAccounts: 6,
    imageAccent: 'zinc-800',
    configFormat: 'grandstream_xml',
  },
  {
    id: 'polycom-vvx450',
    brand: 'Poly (Polycom)',
    model: 'VVX 450',
    displayName: 'Poly VVX 450 12-Line Business Media Phone',
    description: 'Poly HD Voice and Acoustic Fence technology, 4.3" color display, 12 line keys with EM50 expansion capability.',
    screenType: 'Backlit Color LCD 4.3"',
    blfKeys: 12,
    sipAccounts: 12,
    imageAccent: 'neutral-800',
    configFormat: 'polycom_xml',
  },
  {
    id: 'cisco-8851',
    brand: 'Cisco',
    model: '8851',
    displayName: 'Cisco IP Phone 8851 + Key Expansion Module',
    description: 'High-fidelity wideband audio, 5-inch widescreen VGA color display, Gigabit Ethernet, 14-button KEM sidecar.',
    screenType: 'OLED Business',
    blfKeys: 14,
    sipAccounts: 10,
    imageAccent: 'stone-800',
    configFormat: 'cisco_xml',
  },
];

export const INITIAL_OFFICE_MAILS: OfficeMailItem[] = [
  {
    id: 'mail-01',
    callerNumber: '031 361 8700',
    callerName: 'Transnet Port Terminals (Durban Point)',
    timestamp: 'Today, 11:42 AM',
    durationSeconds: 42,
    audioDurationStr: '0:42',
    isRead: false,
    transcription:
      'Hello, this is Sipho from Transnet Durban Pier 2 dispatch. We are calling regarding the customs clearance manifest for container 8492. Please call us back on 031 361 8700 or notify Ext 106 dispatch.',
    urgent: true,
    emailSentTo: 'sello.ncwani@gmail.com',
  },
  {
    id: 'mail-02',
    callerNumber: '031 308 2111',
    callerName: 'Telkom KZN Enterprise Support',
    timestamp: 'Today, 09:15 AM',
    durationSeconds: 31,
    audioDurationStr: '0:31',
    isRead: true,
    transcription:
      'Good morning. This is your Telkom voice engineer confirming that the Durban Metro 031 pilot trunk has completed routing validation. SIP trunk ping latency is optimal at 14ms. Have a productive day.',
    urgent: false,
    emailSentTo: 'sello.ncwani@gmail.com',
  },
  {
    id: 'mail-03',
    callerNumber: '082 899 4321',
    callerName: 'Advocate M. Khumalo (Legal Counsel)',
    timestamp: 'Yesterday, 16:20 PM',
    durationSeconds: 58,
    audioDurationStr: '0:58',
    isRead: true,
    transcription:
      'Good afternoon. Calling regarding the commercial service level agreement documents. I have sent the revised contracts to your main office mail. Kindly confirm receipt at your earliest convenience.',
    urgent: false,
    emailSentTo: 'sello.ncwani@gmail.com',
  },
];

export const INITIAL_CALL_LOGS: CallLogItem[] = [
  {
    id: 'log-01',
    direction: 'inbound',
    number: '031 301 4455',
    name: 'Durban Marine Supplies',
    timestamp: 'Today, 14:18',
    durationSeconds: 145,
    status: 'answered',
    lineId: 'line1',
    providerName: 'Telkom SA',
    recordingAvailable: true,
  },
  {
    id: 'log-02',
    direction: 'outbound',
    number: '011 450 1200',
    name: 'Johannesburg Regional Office',
    timestamp: 'Today, 13:05',
    durationSeconds: 260,
    status: 'answered',
    lineId: 'line1',
    providerName: 'Telkom SA',
  },
  {
    id: 'log-03',
    direction: 'inbound',
    number: '083 412 9900',
    name: 'Vodacom Business KZN Client',
    timestamp: 'Today, 11:40',
    durationSeconds: 42,
    status: 'voicemail',
    lineId: 'line1',
    providerName: 'Vodacom Business',
  },
  {
    id: 'log-04',
    direction: 'inbound',
    number: '031 902 1144',
    name: 'Prospecton Logistics Hub',
    timestamp: 'Today, 10:12',
    durationSeconds: 18,
    status: 'missed',
    lineId: 'line1',
    providerName: 'Telkom SA',
  },
];

export const DEFAULT_PHONE_CONTACTS: PhoneContact[] = [
  {
    id: 'ct-1',
    name: 'Transnet Port Terminals (Pier 1 & 2)',
    phoneNumber: '031 361 8800',
    company: 'Transnet SOC Ltd',
    email: 'operations.dbn@transnet.net',
    category: 'Partner',
    notes: 'Durban Harbour berth allocation & pier dispatch operations',
    isFavorite: true,
    source: 'manual',
  },
  {
    id: 'ct-2',
    name: 'eThekwini Municipal Electricity & Water',
    phoneNumber: '080 311 1111',
    company: 'eThekwini Metro Municipality',
    email: 'contact@durban.gov.za',
    category: 'Supplier',
    notes: 'Emergency municipal utilities fault reporting & central switchboard',
    isFavorite: false,
    source: 'manual',
  },
  {
    id: 'ct-3',
    name: 'Standard Bank Kingsmead Regional',
    phoneNumber: '031 374 1100',
    company: 'Standard Bank Corporate KZN',
    email: 'kzn.corporate@standardbank.co.za',
    category: 'Client',
    notes: 'Durban corporate banking relationship manager',
    isFavorite: true,
    source: 'manual',
  },
  {
    id: 'ct-4',
    name: 'Durban Chamber of Commerce & Industry',
    phoneNumber: '031 335 1000',
    company: 'DCCI Umhlanga',
    email: 'info@durbanchamber.co.za',
    category: 'Client',
    notes: 'Commercial trade desk & maritime sector committee',
    isFavorite: false,
    source: 'manual',
  },
  {
    id: 'ct-5',
    name: 'Telkom SA KZN Enterprise Centre',
    phoneNumber: '031 308 2111',
    company: 'Telkom SA SOC Ltd',
    email: 'kzn.enterprise@telkom.co.za',
    category: 'Supplier',
    notes: 'Durban primary SIP trunk engineer & optical fibre exchange NOC',
    isFavorite: true,
    source: 'manual',
  },
  {
    id: 'ct-6',
    name: 'Dr. Bongani Sithole (KZN Health)',
    phoneNumber: '082 911 4455',
    company: 'Durban Health Services',
    email: 'sithole.b@kznhealth.gov.za',
    category: 'Client',
    notes: 'Occupational health & safety compliance coordinator',
    isFavorite: false,
    source: 'device_phonebook',
  },
];

